### ISSUE TITLE
GridSearch didn't improve the model

### ISSUE THREAD

**Issue by mojtaba-peyrovi** [mojtaba-peyrovi/diabetes-ML-practice#7]
@Donshenal @uta-dsc in order for us to follow up the case of my last pull request and mostly for us to practice more Git, I created this issue. Later on, whoever likes to resolve the issue, can create a new pull request and link it to this issue. I'll try to work on it today.

**Comment by mojtaba-peyrovi** [comment]
With the help of @Donshenal we reached a high accuracy by changing the scoring in GridSearch( ) to "recall"

**Comment by Donshenal** [comment]
We reached a high recall (by changing scoring to recall the best score ouput becomes the recall), 
the precision and therefore also the accuracy dropped a lot by optimizing towards recall, but I think it makes 
sense to optimize the recall rather than the overall accuracy in this case :)

**Comment by mojtaba-peyrovi** [comment]
Correct!
